update

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -32,55 +32,39 @@ runs:
       shell: bash
       id: run-test-plan-action
       run: >
-        set -e
-
         # Mask the value if it is passed in a way other than GitHub secrets
         echo "::add-mask::${{ inputs.autify_for_web_api_token }}"
 
-        run_test_plan() {
-          echo $(curl -s -X POST \
-            -H "Authorization: Bearer ${{ inputs.autify_for_web_api_token }}" \
-            -H "Content-Type: application/json" \
-            "${{ inputs.test_plan_api_base_url }}${{ inputs.test_plan_id }}")
-        }
+        # Validate parameters
+        if [ -z "${{ inputs.autify_for_web_api_token }}" ]; then
+          error "Token should exist"
+          exit 1
+        fi
 
-        validate_parameter() {
-          if [ -z "${{ inputs.autify_for_web_api_token }}" ]; then
-            error "Token should exist"
-            exit 1
-          fi
+        if ! echo "${{ inputs.test_plan_id }}" | grep -Eq '^[0-9]+$'; then
+          echo "Test Plan ID should be string of digits"
+          exit 1
+        fi
 
-          if ! echo "${{ inputs.test_plan_id }}" | grep -Eq '^[0-9]+$'; then
-            echo "Test Plan ID should be string of digits"
-            exit 1
-          fi
-        }
+        # Call API
+        response=$(curl -s -X POST \
+          -H "Authorization: Bearer ${{ inputs.autify_for_web_api_token }}" \
+          -H "Content-Type: application/json" \
+          "${{ inputs.test_plan_api_base_url }}${{ inputs.test_plan_id }}")
 
-        validate_response() {
-          response=$1
+        # Validate response
+        if [[ "$( echo ${response} | jq -R 'fromjson? | has("data")' )" == false ]]; then
+          echo "Something went wrong. The response was :"
+          echo ${response} | jq -R 'fromjson?'
+          exit 1
+        fi
 
-          if [[ "$( echo ${response} | jq -R 'fromjson? | has("data")' )" == false ]]; then
-            echo "Something went wrong. The response was :"
-            echo ${response} | jq -R 'fromjson?'
-            exit 1
-          fi
+        if [ "$( echo ${response} | jq -R 'fromjson? | has("errors")' )" == true ]; then
+          echo "Error running the test plan. The error messages are :"
+          echo ${response} | jq -R 'fromjson?'
+          exit 1
+        fi
 
-          if [ "$( echo ${response} | jq -R 'fromjson? | has("errors")' )" == true ]; then
-            echo "Error running the test plan. The error messages are :"
-            echo ${response} | jq -R 'fromjson?'
-            exit 1
-          fi
-        }
-
-        main() {
-          validate_parameter
-
-          response=$(run_test_plan)
-
-          validate_response ${response}
-
-          echo "Successfully started the Test Plan."
-          echo "::set-output name=response::$(echo ${response})"
-        }
-
-        main "$@"
+        # Outputs
+        echo "Successfully started the Test Plan."
+        echo "::set-output name=response::$(echo ${response})"
